# Generated by Django 4.1.1 on 2022-10-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_participants_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.AddField(
            model_name='event',
            name='messages',
            field=models.ManyToManyField(blank=True, related_name='evmessages', to='event.message'),
        ),
    ]
