# Generated by Django 4.1.1 on 2022-10-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_category_event_participants_event_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['startdatetime', 'enddatetime']},
        ),
        migrations.RemoveField(
            model_name='participant',
            name='event',
        ),
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participants', to='event.participant'),
        ),
    ]
